### ISSUE TITLE
'keyboard de' not working

### ISSUE THREAD

**Issue by taliesin** [noxouille/ubuntu-kickstart-cd-maker#1]
I'm using the script to generate an auto-install ubuntu 18.04.3 server image, however if I change the system keyboard setting to de, instead of us, the installed system still has the us keyboard layout.
Any idea what's going on?

**Comment by noxouille** [comment]
no idea, sorry. Currently I don't have access to linux environment to test it out.

**Comment by taliesin** [comment]
Ubuntu does not seem to support the kickstart stuff properly, so according to https://help.ubuntu.com/lts/installation-guide/s390x/apbs04.html, I use:

preseed --owner d-i console-setup/ask_detect boolean false
preseed --owner d-i keyboard-configuration/xkb-keymap select de
preseed --owner d-i keyboard-configuration/layoutcode string de
preseed --owner d-i keyboard-configuration/variantcode string

Which works.
In general using kickstart for Debian distributions seems 'wrong'. This is particularly true for partitioning issues, see https://ubuntuforums.org/showthread.php?t=2147295

**Comment by noxouille** [comment]
Thanks for letting me know. I don't use any keyboard layout other than US, so I wouldn't have found out about this issue.
